day00/python/fallshare/README.adoc, day00/python/fallshare/solution.py
Getting ready and can't wait for the 1st of December.
@rdmueller thanks for organizing this again this year 😊
=> Fallshare getting ready for AoC 2020!

.gitignore, day00/rust/cakem1x/Cargo.toml, day00/rust/cakem1x/README.adoc, day00/rust/cakem1x/src/main.rs
Besides the hello world program, this PR includes an addition to the `.gitignore` file of this repo.
This change will ignore build artifacts from Rust's build process. I hope this won't ignore some files that shouldn't be ignored in some other context. But the change might be nice for other Rustaceans.
=> Add my day00 "solution" (rust)

day00/wasm-rust/subesokun/Cargo.toml, day00/wasm-rust/subesokun/README.adoc, day00/wasm-rust/subesokun/src/lib.rs, day00/wasm-rust/subesokun/src/solution.rs, day00/wasm-rust/subesokun/www/index.css, day00/wasm-rust/subesokun/www/index.html, day00/wasm-rust/subesokun/www/index.js, day00/wasm-rust/subesokun/www/package-lock.json, day00/wasm-rust/subesokun/www/package.json, day00/wasm-rust/subesokun/www/webpack.config.js
Improve puzzle output with link to day00 solution as GitHub page
=> feat: improve puzzle output

day00/kotlin/SystemQuiesce/day00.kts, day00/kotlin/SystemQuiesce/day00_input.txt
=> Day00 Test and Solution (Kotlin)

day00/python/mschlund/README.adoc, day00/python/mschlund/solution.py, profiles/mschlund.adoc
My first PR -- hello world for AOC
=> First commit

day01/python/mschlund/README.adoc, day01/python/mschlund/solution.py
2- or 3-sum problem, solved using sets (-> hashmaps) in python
=> Solution for Day1

day04/python/jamhocken/README.adoc, day04/python/jamhocken/passports.txt, day04/python/jamhocken/solution.py
Includes solution, README and input file. Checked it on GitPod and looks good to go.
=> Add day04 solution in Python

day05/pytest/cornelius/README.adoc
Fix tag so that README actually shows code for method to decode boarding pass.
=> Fix includes of code

day04/pytest/cornelius/README.adoc, day04/pytest/cornelius/input.txt, day04/pytest/cornelius/test_solution.py
Working backwards through the puzzles, here is a test-driven solution for day 4.
=> Add pytest solution for day 4

day07/python/t-pi/README.adoc, day07/python/t-pi/input07.txt, day07/python/t-pi/solution.py
=> t-pi-day07 @python

day07/python/jamhocken/README.adoc, day07/python/jamhocken/bag_rules.txt, day07/python/jamhocken/solution.py
Runs on Gitpod with no problems.
=> Day 07 solution in Python

day07/python/fallshare/README.adoc, day07/python/fallshare/input.txt, day07/python/fallshare/solution.py
Day07 done - DAGs and Recursion ftw!
=> Day06 done - DAGs and Recursion FTW!

day11/kotlin/RJPlog/README.adoc, day11/kotlin/RJPlog/day2011_1_2.kts
Signed-off-by: RJPlog <tfrenz67@gmail.com>
=> Improvement for solution for day11

day10/python/jamhocken/README.adoc, day10/python/jamhocken/solution.py
The previous version worked with the data from aoc (including all examples), but it still was not correct. I fixed it now.
=> Fixed Day 10 solution in Python and extended docu

day13/kotlin/RJPlog/README.adoc, day13/kotlin/RJPlog/day2013_1_2.kts, day13/kotlin/RJPlog/day2013_puzzle_input.txt
Signed-off-by: RJPlog <tfrenz67@gmail.com>
=> Solution for day13

day13/python/jamhocken/solution.py
Tookover suggestions from @mr-kaffee  and saved even more lines of code as well as an unnecessary flag variable.
=> Refactored Day13 in Python

day13/rust/mr-kaffee/Cargo.toml, day13/rust/mr-kaffee/README.adoc, day13/rust/mr-kaffee/src/lib.rs, day13/rust/mr-kaffee/src/main.rs
Comparison of my solution with @jamhocken's solution lead to some improvements. Also did a runtime comparison with a variant based on @jamhocken's implementation.
=> Improve day13/rust/mr-kaffee and variant

day15/rust/mr-kaffee/Cargo.toml, day15/rust/mr-kaffee/README.adoc, day15/rust/mr-kaffee/src/lib.rs, day15/rust/mr-kaffee/src/main.rs
Signed-off-by: Peter Wieland <peter@die-wielands.net>
=> Solve day15/rust/mr-kaffee

day15/kotlin/RJPlog/README.adoc
My solution was not running on Gitpod due to heap space restriction, Peter found a solution to increase heap space, just added the comment how to do on the readme.
Signed-off-by: RJPlog <tfrenz67@gmail.com>
=> Update README for execution on gitpod.io

day19/rust/mr-kaffee/README.adoc, day19/rust/mr-kaffee/src/lib.rs, day19/rust/mr-kaffee/src/main.rs
Signed-off-by: Peter Wieland <peter@die-wielands.net>
=> Improve solution for day19/rust/mr-kaffee

day13/python/fallshare/README.adoc, day13/python/fallshare/input.txt, day13/python/fallshare/solution.py
=> Day13 - Star 2 final done

day20/rust/mr-kaffee/README.adoc, day20/rust/mr-kaffee/src/lib.rs, day20/rust/mr-kaffee/src/main.rs
Solution variant which does not require searching for corner tiles
Signed-off-by: Peter Wieland <peter@die-wielands.net>
=> Solution variant for day20/rust/mr-kaffee

day23/java/mr-kaffee/Day23.java, day23/java/mr-kaffee/README.adoc, day23/rust/mr-kaffee/Cargo.toml, day23/rust/mr-kaffee/README.adoc, day23/rust/mr-kaffee/src/lib.rs, day23/rust/mr-kaffee/src/main.rs
Signed-off-by: Peter Wieland <peter@die-wielands.net>
=> Solution for day23/java/mr-kaffee

day25/kotlin/RJPlog/README.adoc, day25/kotlin/RJPlog/day2025_1.kts
Signed-off-by: RJPlog <tfrenz67@gmail.com>
=> Solution for day25
